steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/Earls-Discount-System-test/app:$SHORT_SHA', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/Earls-Discount-System-test/app:$SHORT_SHA']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'earls-eccard-app',
      '--image', 'us-east1-docker.pkg.dev/$PROJECT_ID/Earls-Discount-System-test/app:$SHORT_SHA',
      '--platform', 'managed',
      '--region', 'us-east1',
      '--allow-unauthenticated'
    ]

# Set logging to use only Cloud Logging
options:
  logging: NONE

images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/Earls-Discount-System-test/app:$SHORT_SHA'
